### ISSUE TITLE
Android Studio image link is not working !

### ISSUE THREAD

**Issue by Kushal997-das** [akshitagupta15june/akshitagupta15june#2]
https://camo.githubusercontent.com/c3c37dc0a745cab43470bb9d9bd1e6442b58f7e8e96a395963b46ba0d23e8a02/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f332f33342f416e64726f69645f53747564696f5f69636f6e2e737667

**Comment by akshitagupta15june** [comment]
can you explain

**Comment by Kushal997-das** [comment]
> can you explain

>> Sure !

![ans (2)_LI](https://user-images.githubusercontent.com/61356005/110663981-066d7100-81ed-11eb-809c-523dfdf9ce6a.jpg)

**Comment by akshitagupta15june** [comment]
can you work on it

**Comment by Kushal997-das** [comment]
> can you work on it

Sure .
